version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  backend:
